analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 28956,\\n  \\"name\\"\: \\"LinkAjaAndroid\\",\\n  \\"teamId\\"\: 14578,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"team\\"\: {\\n    \\"id\\"\: 14578,\\n    \\"name\\"\: \\"Team LinkAja\\",\\n    \\"organization\\"\: {\\n      \\"id\\"\: 13426,\\n      \\"name\\"\: \\"Organization refqi.hussein\\",\\n      \\"samlSSO\\"\: false\\n    }\\n  },\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
