version: "3.2"
services:
  katalon-agent:
    platform: linux/amd64
    image: "katalonstudio/agent:latest"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_URL: https://testops.katalon.io
      KATALON_USERNAME: refqi.hussein@gmail.com
      AGENT_NAME: "my_docker_agent"
      ORGANIZATION_ID: 13426
      KATALON_API_KEY: 8d39879e-4ec7-4ff0-add9-6d1bf4bad554
      AUTO_UPGRADE_ENVIRONMENT: true
    volumes:
      - katalon-runtime-engines:/root/.katalon

volumes:
  katalon-runtime-engines: