<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeButton - Done</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeButton</value>
      <webElementGuid>98ce9cd4-a996-44bf-a1d3-9cf88fdc3dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0951068-a83e-4580-ab8a-564d0903f786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22243d81-d86d-4cf5-9f96-151bf703af42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>98.0</value>
      <webElementGuid>60ed34e3-b381-406c-9c06-2e9f74411b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>d485dad4-2700-4b99-81b2-c22e173a632d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>261b63bd-4278-4374-b08d-5015bc90da68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>b90d3633-1e29-46c9-a140-cf66786e042a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>204.0</value>
      <webElementGuid>0dad6ec0-ca30-4e25-a252-42c135dcc4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>620.0</value>
      <webElementGuid>0d2a8692-1a85-4461-a4e4-7561cb7d91ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1540.0</value>
      <webElementGuid>992ce833-19e3-4cdb-85d7-71ddd59146a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeButton[3]</value>
      <webElementGuid>b59527c7-9432-4080-b625-e3618a896e86</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeButton' and @label = 'Selesai' and @name = 'Done']</locator>
   <locatorCollection>
      <entry>
         <key>CUSTOM</key>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeButton[`enabled == 1 AND label == 'Selesai' AND name == 'Done'`]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Done</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeButton[3]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeButton' AND enabled == 1 AND label == 'Selesai' AND name == 'Done'</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeButton</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Done</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeButton' and @label = 'Selesai' and @name = 'Done']</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Done</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
