<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeOther - PXGGridLayout-Group</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeOther</value>
      <webElementGuid>8dd19dac-7d28-48f7-95b6-340176dcbc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bcb0fc69-056f-4671-951c-a04e632f3de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4a2671d-1d09-4e4f-b687-3bb194336389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>243204.0</value>
      <webElementGuid>5fe5fd57-b806-43b6-87c9-6b82da747913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ecf2c24-66b2-456d-b75c-55eb1dd682ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Time lapse video, thirty-four seconds, 03 March, 19.37, Video, three minutes, one second, 03 March, 19.34, Photo, 03 March, 19.33, Video, five seconds, 03 March, 19.33, Screenshot, 03 March, 13.26, Screenshot, 03 March, 13.24, Screenshot, 03 March, 11.47, Photo, 02 March, 20.08, Photo, 02 March, 17.44, Screenshot, 02 March, 14.47, Photo, 02 March, 13.17, Photo, 02 March, 13.13, Photo, 02 March, 11.15, Photo, 02 March, 10.58, Photo, 02 March, 09.48</value>
      <webElementGuid>3f983694-3d22-4e33-89d4-bfdedb99b462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PXGGridLayout-Group</value>
      <webElementGuid>ed5c842f-44cb-4e8c-87d3-312192a43cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eddd7a74-cbd0-4274-8b73-4eb10290abde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>828.0</value>
      <webElementGuid>f010090c-f374-45cb-b52a-f0d568028420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>dae73945-6d82-454a-aae6-f08202e90387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>574.0</value>
      <webElementGuid>b9d59eb3-0d6d-4a1b-bf00-00f0b51dbcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]</value>
      <webElementGuid>e8ff867a-ca7e-4563-b334-2aff375aa622</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeOther' and @label = 'Time lapse video, thirty-four seconds, 03 March, 19.37, Video, three minutes, one second, 03 March, 19.34, Photo, 03 March, 19.33, Video, five seconds, 03 March, 19.33, Screenshot, 03 March, 13.26, Screenshot, 03 March, 13.24, Screenshot, 03 March, 11.47, Photo, 02 March, 20.08, Photo, 02 March, 17.44, Screenshot, 02 March, 14.47, Photo, 02 March, 13.17, Photo, 02 March, 13.13, Photo, 02 March, 11.15, Photo, 02 March, 10.58, Photo, 02 March, 09.48' and @name = 'PXGGridLayout-Group']</locator>
   <locatorCollection>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>PXGGridLayout-Group</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>PXGGridLayout-Group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeOther' AND enabled == 1 AND label == 'Time lapse video, thirty-four seconds, 03 March, 19.37, Video, three minutes, one second, 03 March, 19.34, Photo, 03 March, 19.33, Video, five seconds, 03 March, 19.33, Screenshot, 03 March, 13.26, Screenshot, 03 March, 13.24, Screenshot, 03 March, 11.47, Photo, 02 March, 20.08, Photo, 02 March, 17.44, Screenshot, 02 March, 14.47, Photo, 02 March, 13.17, Photo, 02 March, 13.13, Photo, 02 March, 11.15, Photo, 02 March, 10.58, Photo, 02 March, 09.48' AND name == 'PXGGridLayout-Group'</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeOther' and @label = 'Time lapse video, thirty-four seconds, 03 March, 19.37, Video, three minutes, one second, 03 March, 19.34, Photo, 03 March, 19.33, Video, five seconds, 03 March, 19.33, Screenshot, 03 March, 13.26, Screenshot, 03 March, 13.24, Screenshot, 03 March, 11.47, Photo, 02 March, 20.08, Photo, 02 March, 17.44, Screenshot, 02 March, 14.47, Photo, 02 March, 13.17, Photo, 02 March, 13.13, Photo, 02 March, 11.15, Photo, 02 March, 10.58, Photo, 02 March, 09.48' and @name = 'PXGGridLayout-Group']</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeOther</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>PXGGridLayout-Group</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeOther[`enabled == 1 AND label == 'Time lapse video, thirty-four seconds, 03 March, 19.37, Video, three minutes, one second, 03 March, 19.34, Photo, 03 March, 19.33, Video, five seconds, 03 March, 19.33, Screenshot, 03 March, 13.26, Screenshot, 03 March, 13.24, Screenshot, 03 March, 11.47, Photo, 02 March, 20.08, Photo, 02 March, 17.44, Screenshot, 02 March, 14.47, Photo, 02 March, 13.17, Photo, 02 March, 13.13, Photo, 02 March, 11.15, Photo, 02 March, 10.58, Photo, 02 March, 09.48' AND name == 'PXGGridLayout-Group'`]</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
