<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Home (6)</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>0ea0575d-09ae-4cfb-8511-1fcaeb88992b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5157b3d6-33b7-4df0-b564-26a6571dc2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b04b937c-102c-471d-9197-0d741c7981c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28.0</value>
      <webElementGuid>b6ad7f4e-c74a-462f-8042-09775770ffc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>76915dbd-d2ac-4829-b3b1-75cf0be13fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>88b3c4b4-1831-42bd-be65-d68bf576bbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>d2239554-0e6e-47f0-a57c-371746769dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>f60cd9ff-927e-4cc0-8826-5c3eb9803149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>669a9abf-7638-488a-936f-8b5b824860e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>60.0</value>
      <webElementGuid>e66ae8a6-9750-4f27-9dca-66282347e7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>50.0</value>
      <webElementGuid>0f782fe0-f5a1-4cf1-82a4-0ab1496f0187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1684.0</value>
      <webElementGuid>c27c2851-4b25-4a82-8991-72cb8735877b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>2ef5be84-a82a-483e-aa43-76c8d4a7ffc7</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Home' and @name = 'Home' and @value = 'Home']</locator>
   <locatorCollection>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Home' and @name = 'Home' and @value = 'Home']</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Home' AND name == 'Home' AND name == 'Home'</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Home</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Home</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Home</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Home' AND name == 'Home' AND value == 'Home'`]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
